<?xml version="1.0" encoding="UTF-8"?>
<!--
	Populate (update) database with latest cluster state.
	See schema.sql for defintions.
  -->
<x:stylesheet 
	xmlns:x="http://www.w3.org/1999/XSL/Transform" 
	version="1.0">

	<x:output method="text" encoding="UTF-8" />

	<x:template match="/boinc_cluster_state">
		BEGIN;
		<x:apply-templates />		
		COMMIT;
	</x:template>	

	<!-- host_info -->
	<x:template match="host_info">
		INSERT OR REPLACE INTO host (
			updated,
			host_cpid,
			domain_name, 
			hostname,
			p_ncpus,
			p_vendor,
			p_model,
			os_name,
			os_version,
			product_name,
			p_mfpops,
			p_miops
		) VALUES (
			'<x:value-of select="/boinc_cluster_state/@created" />' ,
			'<x:value-of select="host_cpid" />' ,
			'<x:value-of select="domain_name" />' ,
			'<x:value-of select="../../../@hostname" />', <!-- attribute of "boinc_client" element -->		
			<x:value-of select="p_ncpus" /> ,
			'<x:value-of select="p_vendor" />' ,
			'<x:value-of select="p_model" />' ,
			'<x:value-of select="os_name" />' ,
			'<x:value-of select="os_version" />' ,
			'<x:value-of select="product_name" />' ,
			<x:value-of select="round(p_fpops div 1000000)" /> ,
			<x:value-of select="round( p_iops div 1000000)" />
		);
	</x:template>	

	<!-- results in processing, actively or not -->
	<x:template match="result">
		<!-- get related structs -->
		<x:variable name="project"     select="../project[master_url = current()/project_url]" />
		<x:variable name="workunit"    select="../workunit[name = current()/wu_name]" />
		<x:variable name="app_version" select="../app_version[app_name = $workunit/app_name]" />
		<x:variable name="app"         select="../app[name = $workunit/app_name]" />
		<x:variable name="host"        select="../host_info" />

		<x:if test="active_task">
			INSERT INTO task (
				-- task_id is autogenerated, and recalled below with last_insert_rowid()
				fraction_done,
				active_task_state,
				scheduler_state,
				current_cpu_time,
				elapsed_time,
				progress_rate
			) VALUES (
				<x:value-of select="active_task/fraction_done" /> ,
				<x:value-of select="active_task/active_task_state" /> ,
				<x:value-of select="active_task/scheduler_state" /> ,
				<x:value-of select="active_task/current_cpu_time" /> ,
				<x:value-of select="active_task/elapsed_time" /> ,
				<x:choose>
					<x:when test="active_task/progress_rate">
						<x:value-of select="active_task/progress_rate" />
					</x:when>
					<x:otherwise>NULL</x:otherwise>
				</x:choose>
			);			
		</x:if>
		
		INSERT INTO result (
			created,
			name,
			wu_name,
			wu_rsc_mfpops_est,
			host_cpid,
			app_name,
			app_user_friendly_name,
			app_version_num,
			app_version_mflops,
			project_name,
			project_master_url,
			final_cpu_time,
			final_elapsed_time, 
			exit_status,
			state,
			report_deadline,
			received_time,
			estimated_cpu_time_remaining,
			task_id
		) VALUES (
			'<x:value-of select="/boinc_cluster_state/@created" />' ,
			'<x:value-of select="name" />' ,
			'<x:value-of select="wu_name" />' ,
			<x:value-of select="round($workunit/rsc_fpops_est div 1000000)" />,
			'<x:value-of select="$host/host_cpid" />' ,
			'<x:value-of select="$app/name" />' ,
			'<x:value-of select="$app/user_friendly_name" />' ,
			<x:value-of select="$app_version/version_num" /> ,
			<x:value-of select="round($app_version/flops div 1000000)" /> ,
			'<x:value-of select="$project/project_name" />' ,
			'<x:value-of select="$project/master_url" />' ,
			<x:value-of select="final_cpu_time" /> ,
			<x:value-of select="final_elapsed_time" /> ,
			<x:value-of select="exit_status" /> ,
			<x:value-of select="state" /> ,
			<x:value-of select="report_deadline" /> ,
			<x:value-of select="received_time" /> ,
			<x:value-of select="estimated_cpu_time_remaining" /> ,
			<x:choose>
				<x:when test="active_task">last_insert_rowid()</x:when>
				<x:otherwise>NULL</x:otherwise>
			</x:choose>
		);
	</x:template>	

	<!-- ignore stray text in all nodes -->
	<x:template match="text()" />	

</x:stylesheet>
